package com.lattice

/**
 * Column type for schema properties.
 */
enum class LatticeType {
    INTEGER,
    REAL,
    TEXT,
    BLOB
}

/**
 * Property kind for schema properties.
 */
enum class LatticePropertyKind {
    PRIMITIVE,
    LINK,
    LINK_LIST,
    VIRTUAL_LIST,
    VIRTUAL_LINK
}

/**
 * Describes a property in the model schema.
 */
data class LatticePropertyDescriptor(
    val name: String,
    val type: LatticeType,
    val kind: LatticePropertyKind = LatticePropertyKind.PRIMITIVE,
    val nullable: Boolean = false,
    val targetTable: String? = null,  // For links
    val linkTable: String? = null,    // For link lists
    val isIndexed: Boolean = false,   // Create non-unique index
    val isUnique: Boolean = false,    // Create unique constraint
    val isFullText: Boolean = false,  // Create FTS5 virtual table
    val isVector: Boolean = false,    // Create vec0 virtual table
    val isGeoBounds: Boolean = false, // Create R*Tree virtual table
    val columnName: String? = null    // Custom column name mapping
)

/**
 * Interface injected by the compiler plugin into @Model classes.
 *
 * Provides access to the native handle connecting a Kotlin object
 * to its managed representation in the C database layer.
 */
interface LatticeObject {
    /**
     * Native pointer to the managed object.
     * - 0 means unmanaged (property access uses local fields)
     * - Non-zero means managed (property access delegates to native)
     */
    var _latticeHandle: Long

    /**
     * The table name for this model type.
     */
    val _latticeTableName: String

    /**
     * Schema properties for this model type.
     * Generated by the compiler plugin based on the class properties.
     */
    val _latticeSchema: List<LatticePropertyDescriptor>

    /**
     * Copy unmanaged property values to a native object handle.
     * This is called before inserting to copy Kotlin values to native layer.
     * Generated by the compiler plugin.
     */
    fun _copyPropertiesToNative(nativeHandle: Long)

    /**
     * Whether this object is currently managed by a Lattice database.
     */
    val isManaged: Boolean
        get() = _latticeHandle != 0L

    /**
     * The globally unique identifier for this object.
     * Available after the object has been added to a database.
     * Returns null if the object is unmanaged or has no globalId.
     */
    val globalId: String?
        get() {
            if (_latticeHandle == 0L) return null
            return NativeBridge.getStringProperty(_latticeHandle, "globalId")
                .takeIf { it?.isNotEmpty() == true }
        }

    /**
     * The primary key (row ID) for this object.
     * Available after the object has been added to a database.
     * Returns 0 if the object is unmanaged.
     */
    val id: Long
        get() {
            if (_latticeHandle == 0L) return 0L
            return NativeBridge.getIntProperty(_latticeHandle, "id")
        }
}
