package com.lattice

/**
 * Column type for schema properties.
 */
enum class LatticeType {
    INTEGER,
    REAL,
    TEXT,
    BLOB
}

/**
 * Property kind for schema properties.
 */
enum class LatticePropertyKind {
    PRIMITIVE,
    LINK,
    LINK_LIST
}

/**
 * Describes a property in the model schema.
 */
data class LatticePropertyDescriptor(
    val name: String,
    val type: LatticeType,
    val kind: LatticePropertyKind = LatticePropertyKind.PRIMITIVE,
    val nullable: Boolean = false,
    val targetTable: String? = null,  // For links
    val linkTable: String? = null     // For link lists
)

/**
 * Interface injected by the compiler plugin into @Model classes.
 *
 * Provides access to the native handle connecting a Kotlin object
 * to its managed representation in the C database layer.
 */
interface LatticeObject {
    /**
     * Native pointer to the managed object.
     * - 0 means unmanaged (property access uses local fields)
     * - Non-zero means managed (property access delegates to native)
     */
    var _latticeHandle: Long

    /**
     * The table name for this model type.
     */
    val _latticeTableName: String

    /**
     * Schema properties for this model type.
     * Generated by the compiler plugin based on the class properties.
     */
    val _latticeSchema: List<LatticePropertyDescriptor>

    /**
     * Copy unmanaged property values to a native object handle.
     * This is called before inserting to copy Kotlin values to native layer.
     * Generated by the compiler plugin.
     */
    fun _copyPropertiesToNative(nativeHandle: Long)

    /**
     * Whether this object is currently managed by a Lattice database.
     */
    val isManaged: Boolean
        get() = _latticeHandle != 0L
}
